<Level>:
    pos_hint: {'center': (.5, .5)}
    size_hint: None, .8
    width: self.height

    canvas.before:
        Color:
            rgb: .3, .1, .05
        Rectangle:
            pos: self.pos
            size: self.size

<Spawn@Grass>:

<Grass@Tile>:
    canvas.before:
        Color:
            rgb: .1, .7, .15
        Rectangle:
            pos: self.pos
            size: self.size

<Block@Tile>:
    canvas.before:
        Color:
            rgb: .3, .3, .35
        Rectangle:
            pos: self.pos
            size: self.size

<Rock@Tile>:
    canvas.before:
        Color:
            rgb: .1, .1, .15
        Rectangle:
            pos: self.pos
            size: self.size
