<Level>:
    canvas.before:
        Color:
            rgb: .3, .1, .05
        Rectangle:
            pos: self.pos
            size: self.size

<Grass@Tile>:
    canvas.before:
        Color:
            rgb: .1, .7, .15
        Rectangle:
            pos: self.pos
            size: self.size

<Block@Tile>:
    canvas.before:
        Color:
            rgb: .3, .3, .35
        Rectangle:
            pos: self.pos
            size: self.size

<Rock@Tile>:
    canvas.before:
        Color:
            rgb: .1, .1, .15
        Rectangle:
            pos: self.pos
            size: self.size
